version: '3.8'
services:
  app:
    build:
      context: ./be_ecommerce_phone
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - ./be_ecommerce_phone/.env
    environment:
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379

networks:
  default:
    driver: bridge
